FORMAT: 1A

# PROGRAN REST APIs
 
 
# Group E NODE B

## E NODE B Collection [/api/enodeb]

### List all E NODE B [GET]

+ Response 200 (application/json)
      
        [
          {
            "eNBId": 591,
            "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod ornare eros, sit amet euismod mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet pharetra sapien, non interdum ante.",
            "Status": 1,
            "IpAddr": "10.1.49.200",
            "GpsCoordinate": {
              "Latitude": 37.7749290,
              "Longitude": -122.4194160 
            },
            "ProfileArray" :[
              " Profile1",
              " Profile2",
              " Profile3"
            ]
          },
          {
            "eNBId": 592,
            "Description": "Proin et sapien sit amet ligula elementum molestie et eu ligula. Integer non urna vitae velit consectetur volutpat eget hendrerit eros. Nam varius, ex sit amet feugiat condimentum, velit risus iaculis elit, eu hendrerit est tortor eget augue.",
            "Status": 1,
            "IpAddr": "10.1.49.200",
            "GpsCoordinate": {
              "Latitude": 37.4418830,
              "Longitude": -122.1430190 
            },
            "ProfileArray" :[
              " Profile1",
              " Profile2",
              " Profile3"
            ]
          },
          {
            "eNBId": 593,
            "Description": "Nunc quam tortor, ullamcorper at bibendum eget, vehicula eget neque. Maecenas nulla ligula, sodales at venenatis at, vehicula vel nunc. Mauris et tincidunt nisl.",
            "Status": 1,
            "IpAddr": "10.1.49.200",
            "GpsCoordinate": {
              "Latitude": 37.8043640,
              "Longitude": -122.2711140 
            },
            "ProfileArray" :[
              " Profile1",
              " Profile2",
              " Profile3"
            ]
          }

        ]

### Create an E NODE B [PUT]

+ Request (application/json)

        {
          "eNBId": 591,
          "Description": "Maslak-12",
          "IpAddr": "10.1.49.200"
        }


+ Response 200 (application/json)

        {    
          "Result": 1,
          "ErrCode": "Not Registered"
        }

## E NODE B Details [/api/enodeb/{eNBId}]

### Get one E NODE B [GET]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to retrieve

+ Response 200 (application/json)

        {
          "eNBId": 591,
          "Description": "Maslak-12",
          "Status": 1,
          "IpAddr": "10.1.49.200",
          "GpsCoordinate": {
            "Latitude": 37.492425,
            "Longitude": 127.031008
          },
          "ProfileArray" :[
            " Profile1",
            " Profile2",
            " Profile3"
          ]
        }

### Delete one E NODE B [DELETE]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to delete

+ Response 204

## E NODE B Profiles Collection [/api/enodeb/{eNBId}/profile]

### Get a Profile list associated to E NODE B [GET]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to retrieve

+ Response 200 (application/json)
      
        [
          {
            "Name": "Profile-30",
            "DlSchedType": "RR",
            "DlAllocRBRate": 10,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-31",
            "DlSchedType": "RR",
            "DlAllocRBRate": 20,
            "UlSchedType": "RR",
            "UlAllocRBRate": 10,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-32",
            "DlSchedType": "RR",
            "DlAllocRBRate": 45,
            "UlSchedType": "RR",
            "UlAllocRBRate": 5,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          }
        ]

### Add an Profile to E NODE B [PUT]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to retrieve

+ Request (application/json)

        {
          "ProfileArray" :[
            "Profile1",
            "Profile2"
          ]
        }
+ Response 200 (application/json)

        {    
          "Result": 1,
          "ErrCode": "Not Registered"
        }

### Delete all Profile from E NODE B [DELETE]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to retrieve

+ Response 204

## E NODE B Profiles Details [/api/profile/{eNBId}/{profile_name}]

### Delete one Profile from E NODE B [DELETE]

+ Parameters
    + eNBId: 591 (number) - Number of the E NODE B to retrieve
    + profile_name: "Profile-30" (string) - Name of the Profiles

+ Response 204


 
 
# Group IMSI 

Imsi is basic phone number object.
Before adding any imsi to profile (Refer to 2.5 ), it must be created.

## IMSI Collection [/api/imsi]

### List all IMSI [GET]

+ Response 200 (application/json)

        [
          {
            "IMSI": "001020123456275",
            "UeStatus": 0,
            "Enodeb": "Enodeb-310",
            "DlMeasBitRate": 10000000,
            "UlMeasBitRate": 10000000
          }
        ]


### Create an IMSI [PUT]

+ Request (application/json)

        {
            "IMSI": "001020123456273"
        }

+ Response 200 (application/json)

        {    
          "Result": 1,
          "ErrCode": "Not Registered"
        }

## IMSI Details [/api/imsi/{imsi_number}]

### Get one IMSI [GET]

+ Parameters
    + imsi_number: "001020123456275" (string) - Number of the IMSI to retrieve

+ Response 200 (application/json)

        {
          "IMSI": "001020123456275",
          "UeStatus": 0,
          "Enodeb": "Enodeb-310",
          "DlMeasBitRate": 10000000,
          "UlMeasBitRate": 10000000
        }

### Delete one IMSI [DELETE]

+ Parameters
    + imsi_number: "001020123456275" (string) - Number of the IMSI to delete

+ Response 204
 
## IMSI Profiles [/api/imsi/{imsi_number}/profile]

### Profile Name associated with Imsi [GET]

+ Parameters
    + imsi_number: "001020123456275" (string) - Number of the IMSI

+ Response 200 (application/json)

        [
          {
            "Name": "Profile-30",
            "DlSchedType": "RR",
            "DlAllocRBRate": 10,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-31",
            "DlSchedType": "RR",
            "DlAllocRBRate": 20,
            "UlSchedType": "RR",
            "UlAllocRBRate": 10,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-32",
            "DlSchedType": "RR",
            "DlAllocRBRate": 45,
            "UlSchedType": "RR",
            "UlAllocRBRate": 5,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          }
        ]
        
## IMSI Profiles Details [/api/profile/{imsi_number}/{profile_name}]

### Delete one Profile from E NODE B [DELETE]

+ Parameters
    + imsi_number: "001020123456275" (string) - Number of the IMSI to retrieve
    + profile_name: "Profile-30" (string) - Name of the Profiles

+ Response 204
 
 
# Group Profiles

## Profiles Collection [/api/profile]

### List all Profiles [GET]

+ Response 200 (application/json)
      
        [
          {
            "Name": "Profile-30",
            "DlSchedType": "RR",
            "DlAllocRBRate": 30,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-31",
            "DlSchedType": "RR",
            "DlAllocRBRate": 30,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          },
          {
            "Name": "Profile-32",
            "DlSchedType": "RR",
            "DlAllocRBRate": 30,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0,
            "CellIndividualOffset": 0, 
            "Handover": {
              "A3offset": 2,
              "HysteresisA3": 1,
              "A5TriggerType": 0,
              "Rsrq": 1,
              "A5Thresh1Rsrp": -97,
              "A5Thresh1Rsrq": -10,
              "A5Thresh2Rsrp": -95,
              "A5Thresh2Rsrq": -8,
              "HysteresisA5": 1
            },
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          }
        ]

### Create an Profiles [PUT]

+ Request (application/json)

        {
          "Name" : "Profile-30",
          "DlSchedType"   : "RR",
          "DlAllocRBRate" : 30,
          "UlSchedType"   : "RR",
          "UlAllocRBRate" : 30,
          "Start": "15/05/2015 9:00",
          "End" :"15/05/2015 18:00",
          "AdmControl : 0,
          "CellIndividualOffset:0, 
          "Handover": {
            "A3offset"      : 2,
            "HysteresisA3"  : 1,
            "A5TriggerType" : 0,
            "Rsrq" : 1,
            "A5Thresh1Rsrp" : -97,
            "A5Thresh1Rsrq" : -10,
            "A5Thresh2Rsrp" : -95,
            "A5Thresh2Rsrq" : -8,
            "HysteresisA5"  : 1
          }
        }



+ Response 200 (application/json)

        {    
          "Result": 1,
          "ErrCode": "Not Registered"
        }

## Profiles Details [/api/profile/{profile_name}]

### Get one Profiles [GET]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to retrieve

+ Response 200 (application/json)

        {
            "Name": "Profile-30"
            "DlSchedType": "RR",
            "DlAllocRBRate": 30,
            "UlSchedType": "RR",
            "UlAllocRBRate": 30,
            "Start": "15/05/2015 9:00",
            "End": "15/05/2015 18:00",
            "AdmControl": 0
            "CellIndividualOffset": 0, 
            "Handover"    : {
              "A3offset"      : 2,
              "HysteresisA3"  : 1,
              "A5TriggerType" : 0,
              "Rsrq" : 1,
              "A5Thresh1Rsrp" : -97,
              "A5Thresh1Rsrq" : -10,
              "A5Thresh2Rsrp" : -95,
              "A5Thresh2Rsrq" : -8,
              "HysteresisA5"  : 1,
            }
            "IMSIRuleArray" : [
              "001020123456273",
              "001020123456272" 
            ]
          }

### Delete one Profiles [DELETE]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to delete

+ Response 204

## Profiles IMSI's Collection [/api/profile/{profile_name}/imsi]

### Add an IMSI to a Profile [PUT]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to retrieve

+ Request (application/json)

        {
          "IMSIRuleArray" : [
            "001020123456273",
            "001020123456272"
          ]
        }
+ Response 200 (application/json)

        {    
          "Result": 1,
          "ErrCode": "Not Registered"
        }

### Delete all IMSI from a Profile [DELETE]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to retrieve

+ Response 204

## Profiles IMSI's Details [/api/profile/{profile_name}/{imsi_number}]

### Delete one IMSI from a Profile [DELETE]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to retrieve
    + imsi_number: "001020123456275" (string) - Number of the IMSI

+ Response 204

 
 
# Group Stats

# IMSI stats [/api/stats/imsi/{imsi}/{counts}]

### Get Stats [GET]

+ Parameters
    + imsi: "001020123456275" (string) - Number of the IMSI to retrieve
    + counts: "10" (string) - Value can be 10, 20 or  "mean"

+ Response 200 (application/json)
      
        [
          {
            "Time"      :   123333 
            "DlBitrate" :   10,
            "UlBitrate" :   20
          },
          {
            "Time"      :   127333
            "DlBitrate" :   8,
            "UlBitrate" :   0
          }
        ]

## Profile stats [/api/stats/profile/{profile_name}/{counts}]

### Get Stats [GET]

+ Parameters
    + profile_name: "Profile-30" (string) - Name of the Profiles to retrieve
    + counts: "10" (string) - Value can be 10, 20 or  "mean"

+ Response 200 (application/json)
      
        [
          {
            "Enodeb"  : 312,
            "StatsArray" :[
              { 
                "Time"      :   123333
                "DlBitrate" :   10,
                "UlBitrate" :   20 
              },
              {
                "Time"      :   126333
                "DlBitrate" :   8,
                "UlBitrate" :   0 
              }
            ]
          },
          {
            "Enodeb"  : 315,
            "StatsArray" :[
                {
                  "Time"      :   127333
                  "DlBitrate" :   10,
                  "UlBitrate" :   20 
                },
                {
                  "Time"      :   129333
                  "DlBitrate" :   8,
                  "UlBitrate" :   0 
                }
              }
            ]
          }
        ]

## E NODE B stats [/api/stats/enodeb/{eNBId}/{counts}]

### Get Stats [GET]

+ Parameters
    + eNBId: "591" (string) - Name of the Profiles to retrieve
    + counts: "10" (string) - Value can be 10, 20 or  "mean"

+ Response 200 (application/json)

        {
          "ConnectedUE": 246,
          "ActiveProfiles": 827,
          "TotalProfiles": 827,
          "Uptime": 293894,
          "ProfileArray": [
            {
              "Profile"  : "Profile-1",
              "StatsArray" :[
                {
                  "Time"      :   1464990095,
                  "DlBitrate" :   10,
                  "UlBitrate" :   20 
                },
                {
                  "Time"      :   1464986495,
                  "DlBitrate" :   10,
                  "UlBitrate" :   30 
                },
                {
                  "Time"      :   1464982895,
                  "DlBitrate" :   8,
                  "UlBitrate" :   10 
                }
              ]
            },
            {
              "Profile"  : "Profile-2",
              "StatsArray" :[
                {
                  "Time"      :   1464990095,
                  "DlBitrate" :   13,
                  "UlBitrate" :   25 
                },
                {
                  "Time"      :   1464986495,
                  "DlBitrate" :   10,
                  "UlBitrate" :   12 
                },
                {
                  "Time"      :   1464982895,
                  "DlBitrate" :   4,
                  "UlBitrate" :   26 
                }
              ]
            }
          ]
        }

